dataset: 'humaneva'
t_his: 15
t_pred: 60
batch_size: 256
num_epoch: 501
milestone: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
num_data_sample: 50000
num_val_data_sample: 5000
lr: 6.e-4
n_pre: 15
multimodal_path: ./data/humaneva_multi_modal/t_his15_1_thre0.500_t_pred60_thre0.010_index_filterd.npz
data_candi_path: ./data/humaneva_multi_modal/data_candi_t_his15_t_pred60_skiprate15.npz
padding: 'LastFrame'
num_layers: 4
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 0.5
mod_test: 1.
cfg_scale: 0.5
use_dct: True
dct_norm_enable: False
resume: False
ckpt_path: ""
frame_mask: False
joint_mask: False
residual_data: False
random_sample: False
cross_attention: False
stylization_block: False
flash_attention: True
se_layer: False
skip_type: 'concat'
model_name: 'MotioniTransformer'
